# Generated by Django 6.0.2 on 2026-02-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alquiler', 'Alquiler'), ('venta', 'Venta'), ('administracion', 'Administración')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pendiente', 'Pendiente'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_gestion', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contrato de Gestión',
                'verbose_name_plural': 'Contratos de Gestión',
                'db_table': 'contratos_gestion',
            },
        ),
    ]
