# Generated by Django 6.0.2 on 2026-02-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_gestion', to='propiedades.propiedad'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['cliente', 'estado'], name='contratos_g_cliente_aa6b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['propiedad', 'estado'], name='contratos_g_propied_ae5d09_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['fecha_inicio'], name='contratos_g_fecha_i_ef5b3b_idx'),
        ),
    ]
