# Generated by Django 6.0.2 on 2026-02-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('contratos', '0001_initial'),
        ('propiedades', '0002_alter_propiedad_operacion_alter_videopropiedad_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='porcentaje_comision',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje aplicado sobre el monto total', max_digits=5, null=True, verbose_name='Porcentaje de Comisión'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto calculado automáticamente (monto × porcentaje_comision ÷ 100)', max_digits=12, null=True, verbose_name='Comisión Calculada'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['cliente', 'estado'], name='contratos_g_cliente_aa6b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['propiedad', 'estado'], name='contratos_g_propied_ae5d09_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['fecha_inicio'], name='contratos_g_fecha_i_ef5b3b_idx'),
        ),
    ]
