# Generated by Django 6.0.2 on 2026-02-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_gestion', to='propiedades.propiedad'),
        ),
    ]
