# Generated by Django 6.0.4 on 2026-04-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
