# Generated by Django 6.0.2 on 2026-02-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la tarea')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de finalización estimada')),
                ('fecha', models.DateField(verbose_name='Fecha de la tarea')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=5, verbose_name='Prioridad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción detallada')),
                ('finalizada', models.BooleanField(default=False, verbose_name='¿Tarea finalizada?')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de finalización')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
