# Generated by Django 6.0.2 on 2026-02-27 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='empleados',
            field=models.ManyToManyField(related_name='tareas', to=settings.AUTH_USER_MODEL, verbose_name='Empleados asignados'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['fecha', 'finalizada'], name='tareas_tare_fecha_1472c5_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['prioridad', 'finalizada'], name='tareas_tare_priorid_4e86fb_idx'),
        ),
    ]
