# Generated by Django 6.0.4 on 2026-04-20 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_tarea_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='creador',
        ),
    ]
