# Generated by Django 5.2.7 on 2025-10-30 19:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('domicilio', models.CharField(max_length=255, verbose_name='Domicilio')),
                ('ciudad', models.CharField(default='Salta', max_length=100, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('categoria', models.CharField(choices=[('alquiler', 'Alquiler'), ('compra', 'Compra'), ('venta', 'Venta'), ('ambos', 'Alquiler y Compra')], max_length=20, verbose_name='Categoría')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('prospecto', 'Prospecto'), ('convertido', 'Convertido')], default='prospecto', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('presupuesto_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto Mínimo')),
                ('presupuesto_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto Máximo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('agente_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['agente', 'administrador']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['dni'], name='clientes_cl_dni_5e5da9_idx'), models.Index(fields=['email'], name='clientes_cl_email_eae461_idx'), models.Index(fields=['estado'], name='clientes_cl_estado_54796b_idx'), models.Index(fields=['categoria'], name='clientes_cl_categor_6ea3bc_idx')],
            },
        ),
    ]
