# Generated by Django 6.0.2 on 2026-02-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(choices=[('alquiler', 'Inquilino'), ('compra', 'Comprador'), ('venta', 'Venta'), ('ambas', 'Ambos (Inquilino/Comprador)')], max_length=20, verbose_name='Categoría'),
        ),
    ]
