# Generated by Django 6.0.2 on 2026-02-27 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='agente_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['agente', 'administrador']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['dni'], name='clientes_cl_dni_5e5da9_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['email'], name='clientes_cl_email_eae461_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['estado'], name='clientes_cl_estado_54796b_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['categoria'], name='clientes_cl_categor_6ea3bc_idx'),
        ),
    ]
