# Generated by Django 6.0.2 on 2026-02-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/imagenes/%Y/%m/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Imagen Principal')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
            ],
            options={
                'verbose_name': 'Imagen de Propiedad',
                'verbose_name_plural': 'Imágenes de Propiedades',
                'ordering': ['orden', '-es_principal'],
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Publicación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('terreno', 'Terreno'), ('local', 'Local Comercial'), ('oficina', 'Oficina')], max_length=20, verbose_name='Tipo de Propiedad')),
                ('operacion', models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler')], max_length=20, verbose_name='Tipo de Operación')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('vendida', 'Vendida'), ('alquilada', 'Alquilada'), ('inactiva', 'Inactiva')], default='disponible', max_length=20, verbose_name='Estado')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de Venta')),
                ('precio_alquiler', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Alquiler')),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('ARS', 'Pesos')], default='USD', max_length=10, verbose_name='Moneda')),
                ('superficie_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Superficie Total (m²)')),
                ('superficie_cubierta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie Cubierta (m²)')),
                ('dormitorios', models.PositiveIntegerField(default=0, verbose_name='Dormitorios')),
                ('banos', models.PositiveIntegerField(default=0, verbose_name='Baños')),
                ('cocheras', models.PositiveIntegerField(default=0, verbose_name='Cocheras')),
                ('antiguedad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Antigüedad (años)')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('barrio', models.CharField(max_length=100, verbose_name='Barrio')),
                ('ciudad', models.CharField(default='Salta', max_length=100, verbose_name='Ciudad')),
                ('provincia', models.CharField(default='Salta', max_length=100, verbose_name='Provincia')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('zona', models.CharField(choices=[('norte', 'Norte'), ('sur', 'Sur'), ('este', 'Este'), ('oeste', 'Oeste'), ('micro-centro', 'Micro Centro'), ('macro-centro', 'Macro Centro')], max_length=20, verbose_name='Zona')),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitud')),
                ('caracteristicas', models.TextField(blank=True, help_text='Una por línea', verbose_name='Características Principales')),
                ('destacada', models.BooleanField(default=False, verbose_name='Propiedad Destacada')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('vistas', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='VideoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='propiedades/videos/%Y/%m/', verbose_name='Video')),
                ('url_youtube', models.URLField(blank=True, verbose_name='URL de YouTube')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('miniatura', models.ImageField(blank=True, upload_to='propiedades/miniaturas/%Y/%m/', verbose_name='Miniatura')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
            ],
            options={
                'verbose_name': 'Video de Propiedad',
                'verbose_name_plural': 'Videos de Propiedades',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
