# Generated by Django 6.0.2 on 2026-02-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='operacion',
            field=models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler')], max_length=20, verbose_name='Tipo de Operación'),
        ),
        migrations.AlterField(
            model_name='videopropiedad',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='propiedades/videos/%Y/%m/', verbose_name='Video'),
        ),
    ]
