# Generated by Django 6.0.2 on 2026-02-27 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('propiedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='agente_cargo',
            field=models.ForeignKey(limit_choices_to={'rol__in': ['agente', 'administrador']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades_cargo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='imagenpropiedad',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.propiedad'),
        ),
        migrations.AddField(
            model_name='videopropiedad',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='propiedades.propiedad'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['tipo', 'operacion'], name='propiedades_tipo_34f7fa_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['estado'], name='propiedades_estado_79f814_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['zona', 'barrio'], name='propiedades_zona_5f7f15_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['destacada'], name='propiedades_destaca_1d3722_idx'),
        ),
    ]
