# Generated by Django 6.0.4 on 2026-04-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopropiedad',
            name='url_youtube',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL de YouTube'),
        ),
    ]
