# Generated by Django 6.0.2 on 2026-02-27 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la visita')),
                ('hora', models.TimeField(verbose_name='Hora de la visita')),
                ('resultado', models.CharField(blank=True, choices=[('interesado', 'Cliente Interesado'), ('no_interesado', 'Cliente No Interesado'), ('agendada_visita', 'Se agendó nueva visita'), ('vendido', 'Se concretó venta/alquiler'), ('no_se_presento', 'No se presentó el cliente')], help_text='Resultado obtenido de la visita', max_length=20, null=True, verbose_name='Resultado')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles de lo tratado en la visita', verbose_name='Descripción de la visita')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('hora_finalizacion', models.TimeField(blank=True, null=True, verbose_name='Hora de finalización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='clientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-fecha', '-hora'],
                'indexes': [models.Index(fields=['cliente', 'fecha'], name='visitas_vis_cliente_a4ee5d_idx'), models.Index(fields=['estado'], name='visitas_vis_estado_074c3a_idx'), models.Index(fields=['fecha', 'hora'], name='visitas_vis_fecha_0b295b_idx'), models.Index(fields=['fecha_creacion'], name='visitas_vis_fecha_c_2a3f10_idx')],
            },
        ),
    ]
