# Generated by Django 6.0.2 on 2026-02-27 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_categoria'),
        ('visitas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='calificacion',
        ),
        migrations.AddField(
            model_name='visita',
            name='hora_finalizacion',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de finalización'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='resultado',
            field=models.CharField(blank=True, choices=[('interesado', 'Cliente Interesado'), ('no_interesado', 'Cliente No Interesado'), ('agendada_visita', 'Se agendó nueva visita'), ('vendido', 'Se concretó venta/alquiler'), ('no_se_presento', 'No se presentó el cliente')], help_text='Resultado obtenido de la visita', max_length=20, null=True, verbose_name='Resultado'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['fecha_creacion'], name='visitas_vis_fecha_c_2a3f10_idx'),
        ),
    ]
