# Generated by Django 6.0.4 on 2026-04-14 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('visitas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='empleado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['agente', 'administrador']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Empleado asignado'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['empleado', 'fecha', 'hora'], name='visitas_vis_emplead_66f637_idx'),
        ),
    ]
