# Generated by Django 6.0.4 on 2026-04-16 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('propiedades', '0002_initial'),
        ('visitas', '0002_visita_empleado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, help_text='Mensaje opcional del cliente al solicitar la visita', verbose_name='Mensaje del cliente')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_visita', to='clientes.cliente', verbose_name='Cliente solicitante')),
                ('procesado_por', models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['agente', 'administrador']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_visita', to='propiedades.propiedad', verbose_name='Propiedad solicitada')),
                ('visita_creada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='visitas.visita', verbose_name='Visita creada')),
            ],
            options={
                'verbose_name': 'Solicitud de Visita',
                'verbose_name_plural': 'Solicitudes de Visita',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['cliente', 'estado'], name='visitas_sol_cliente_3dc6b0_idx'), models.Index(fields=['propiedad', 'estado'], name='visitas_sol_propied_27616d_idx'), models.Index(fields=['estado', 'fecha_creacion'], name='visitas_sol_estado_a48130_idx'), models.Index(fields=['procesado_por'], name='visitas_sol_procesa_54cf12_idx')],
            },
        ),
    ]
