# Generated by Django 6.0.2 on 2026-02-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='barrio',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, default='Salta', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad_interes',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad de Interés'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intereses',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Intereses'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numeracion',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Numeración'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puesto',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Puesto'),
        ),
    ]
