# Generated by Django 6.0.2 on 2026-02-27 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler')], max_length=20, verbose_name='Tipo de Contrato')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número de Contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Total')),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('ARS', 'Pesos')], default='USD', max_length=10, verbose_name='Moneda')),
                ('monto_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Mensual')),
                ('deposito_garantia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Depósito de Garantía')),
                ('archivo_contrato', models.FileField(blank=True, upload_to='contratos/%Y/%m/', verbose_name='Archivo del Contrato')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('numero_cuota', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Cuota')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Pagado')),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('ARS', 'Pesos')], default='USD', max_length=10, verbose_name='Moneda')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('mercadopago', 'Mercado Pago'), ('otro', 'Otro')], max_length=20, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('parcial', 'Pago Parcial'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('numero_comprobante', models.CharField(blank=True, max_length=100, verbose_name='Número de Comprobante')),
                ('archivo_comprobante', models.FileField(blank=True, upload_to='comprobantes/%Y/%m/', verbose_name='Comprobante de Pago')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['fecha_vencimiento', '-fecha_registro'],
            },
        ),
    ]
