# Generated by Django 6.0.2 on 2026-02-27 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('pagos', '0001_initial'),
        ('propiedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='agente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_gestionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='propiedades.propiedad'),
        ),
        migrations.AddField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='pago',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pagos.contrato'),
        ),
        migrations.AddField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['numero_contrato'], name='pagos_contr_numero__de74c1_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['cliente', 'estado'], name='pagos_contr_cliente_174571_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['propiedad'], name='pagos_contr_propied_484a34_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['contrato', 'estado'], name='pagos_pago_contrat_bd59ff_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['cliente', 'estado'], name='pagos_pago_cliente_01e94c_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_vencimiento'], name='pagos_pago_fecha_v_9d409c_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado'], name='pagos_pago_estado_c1c831_idx'),
        ),
    ]
