# Generated by Django 6.0.2 on 2026-02-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada Telefónica'), ('email', 'Correo Electrónico'), ('whatsapp', 'WhatsApp'), ('reunion', 'Reunión'), ('visita', 'Visita a Propiedad'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Seguimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Programada')),
                ('fecha_realizada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Realizada')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción/Notas')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado')),
                ('requiere_seguimiento', models.BooleanField(default=False, verbose_name='Requiere Seguimiento')),
                ('proxima_accion', models.TextField(blank=True, verbose_name='Próxima Acción')),
                ('fecha_proximo_contacto', models.DateField(blank=True, null=True, verbose_name='Fecha Próximo Contacto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha_programada', '-fecha_creacion'],
            },
        ),
    ]
