# Generated by Django 5.2.7 on 2025-10-30 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('propiedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada Telefónica'), ('email', 'Correo Electrónico'), ('whatsapp', 'WhatsApp'), ('reunion', 'Reunión'), ('visita', 'Visita a Propiedad'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Seguimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Programada')),
                ('fecha_realizada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Realizada')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción/Notas')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado')),
                ('requiere_seguimiento', models.BooleanField(default=False, verbose_name='Requiere Seguimiento')),
                ('proxima_accion', models.TextField(blank=True, verbose_name='Próxima Acción')),
                ('fecha_proximo_contacto', models.DateField(blank=True, null=True, verbose_name='Fecha Próximo Contacto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_realizados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='clientes.cliente')),
                ('propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to='propiedades.propiedad')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha_programada', '-fecha_creacion'],
                'indexes': [models.Index(fields=['cliente', 'estado'], name='seguimiento_cliente_7fb5cb_idx'), models.Index(fields=['fecha_programada'], name='seguimiento_fecha_p_d55c0d_idx'), models.Index(fields=['agente', 'estado'], name='seguimiento_agente__74b9d9_idx')],
            },
        ),
    ]
