# Generated by Django 6.0.2 on 2026-02-27 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('propiedades', '0002_initial'),
        ('seguimientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='agente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Agente asignado'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to='propiedades.propiedad', verbose_name='Propiedad relacionada'),
        ),
        migrations.AddIndex(
            model_name='seguimiento',
            index=models.Index(fields=['cliente', 'estado'], name='seguimiento_cliente_7fb5cb_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimiento',
            index=models.Index(fields=['fecha_programada'], name='seguimiento_fecha_p_d55c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimiento',
            index=models.Index(fields=['agente', 'estado'], name='seguimiento_agente__74b9d9_idx'),
        ),
    ]
